window.MYSUNI_REFERENCE_DATA = window.MYSUNI_REFERENCE_DATA || {};
window.MYSUNI_REFERENCE_DATA.defaultGlossary = [
  ["mySUNI 총장-임원 Bi-Weekly", "mySUNI President Bi-Weekly Meeting"],
  ["mySUNI 운영위원회", "mySUNI Steering Committee"],
  ["mySUNI 운영소위원회", "mySUNI Steering Subcommittee"],
  ["의장 Quarterly", "Chairman Quarterly Meeting"],
  ["경영전략회의", "Management Strategy Meeting"],
  ["변화추진", "Change Enablement"],
  ["AI역량육성", "AI Talent Enablement"],
  ["경영관리역량", "Business Management Competency"],
  ["러닝플랫폼", "Learning Platform"],
  ["미래반도체", "Future Semiconductor"],
  ["SKMS실천", "SKMS Implementation"],
  ["리더십개발(담당)", "Leadership Development"],
  ["SK 아카데미", "SK Academy"],
  ["육성/조직문화", "Talent Development & Organizational Culture"],
  ["멤버사", "Member Company"],
  ["구성원", "SK People, Member"],
  ["전문교수단", "Expert Faculty Group"],
  ["협의회", "SUPEX Council"],
  ["HR 지원팀", "HR Supporting Team"],
  ["전입구성원 온보딩 교육", "Onboarding Program for [Participants/Target Audience]"],
  ["팀장 리더십 캠프", "Team Leader Leadership Camp"],
  ["신임임원과정", "New Executive Program"],
  ["임원 과정", "Executive Program"],
  ["ELP", "Executive Leadership Program"],
  ["FLP", "Future Leadership Program"],
  ["HLP", "High-Potential Leadership Program"],
  ["ILP", "Ignite Leadership Program"],
  ["GLP", "Global Leadership Program"],
  ["조직효과성 진단", "Organizational Effectiveness Assessment"],
  ["리더십 진단", "Leadership Assessment"],
  ["회장", "Top Management (TM)"],
  ["의장", "Chairman"],
  ["총장", "President of mySUNI"],
  ["담당", "Head of ~ Department"],
  ["원장", "Director of SK Academy"],
  ["이사회 의장", "Chair of the Board"],
  ["사외이사", "Outside Director"],
  ["이사회사무국", "Office of the Board of Directors"],
  ["멤버사의 본부장", "Head of ~ Division"],
  ["실장", "Head of ~ Office"],
  ["무의 연수원", "SK Muui Training Center"],
  ["수송스퀘어", "Susong Office"],
  ["수송스퀘어 14층 선재당", "Sunjaedang, 14F, Susong Office"],
  ["서린", "Seorin Office"],
  ["워커힐 아카디아", "Arcadia, Walkerhill Hotel"],
  ["워커힐 웨이브힐", "Wavehill, Walkerhill Hotel"],
  ["SK아카데미(용인)", "SK Academy (Yongin)"],
  ["SKT인재개발원(이천)", "SKT Talent Development Institute (Icheon)"]
];

window.MYSUNI_REFERENCE_DATA.defaultNames = [
  ["박상규", "Simon Park"],
  ["은현지", "Jay Eun"],
  ["성용모", "Morgan Sung"],
  ["우창수", "Jude Woo"],
  ["조만희", "Joe Jo"],
  ["강세현", "Senny Kang"],
  ["김세빈", "Logan Kim"],
  ["이솔", "Summer Lee"],
  ["임선영", "Celine Lim"],
  ["정용준", "Mohammed bin Yongjun Jeong"],
  ["강현이", "Michaela Kang"],
  ["김현수", "Hans Kim"],
  ["박종민", "Noah Park"],
  ["신현택", "Sean Shin"],
  ["박미라", "Leah Park"],
  ["이슬기", "Sophia Lee"],
  ["김서연", "Anne Kim"],
  ["강병준", "Luca Kang"],
  ["문태호", "Thomas Moon"],
  ["조영찬", "Aiden Jo"],
  ["조인후", "Joey Cho"],
  ["이승훈", "Justin Lee"],
  ["양다은", "Olivia Yang"],
  ["박귀애", "Anne Park"],
  ["김다예", "Danielle Kim"],
  ["김인혜", "Ines Kim"],
  ["문가은", "Gaelle Moon"],
  ["이화연", "Gloria Lee"],
  ["백지연", "Elsa Baik"],
  ["조민호", "David Jo"],
  ["김남연", "Anna Kim"],
  ["김주희", "Julie Kim"],
  ["양하준", "Jun Yang"],
  ["추현준", "Shane Chu"],
  ["김혜진", "Jin Kim"],
  ["장활훈", "James Jang"],
  ["최윤홍", "Uni Choi"],
  ["김선아", "Sara Kim"],
  ["이규영", "Shawn Lee"],
  ["김민경", "Megan Kim"],
  ["김동규", "Ben Kim"],
  ["김상규", "Jaden Kim"],
  ["이승준", "Chris Rhie"],
  ["신용환", "Andrew Shin"],
  ["전유진", "Erica Jeon"],
  ["정소미", "Ella Jeong"],
  ["최원정", "Joy Choi"],
  ["진선미", "Mia Jean"],
  ["류태호", "Lucas Ryu"],
  ["임성하", "Olive Lim"],
  ["조한나", "Hannah Cho"],
  ["김재윤", "Joey Kim"],
  ["고유진", "Irene Koh"],
  ["김보경", "Katie Kim"],
  ["김송이", "Song Kim"],
  ["심희연", "May Shim"],
  ["박서현", "Ellie Park"],
  ["박은경", "Erika Park"],
  ["안정민", "Ash An"],
  ["오하나", "Hana Oh"],
  ["이수지", "Suzy Lee"],
  ["이상진", "Leo Lee"],
  ["조혜경", "Hailey Cho"],
  ["최원기", "Kai Choi"],
  ["이송만", "Kevin Lee"],
  ["홍종호", "Damon Hong"],
  ["김호섭", "Henry Kim"],
  ["임규남", "Charlie Im"],
  ["김진택", "Brian Kim"],
  ["윤언철", "Paul Yoon"],
  ["임창현", "Chris Im"],
  ["권석균", "Aaron Kwon"],
  ["이희진", "Jenny Lee"],
  ["정재한", "Jeremy Jeong"],
  ["여규원", "Lena Yoh"],
  ["이경란", "Nora Lee"],
  ["송일섭", "Joseph Song"],
  ["박성진", "Sung Park"],
  ["최유현", "Alice Choi"],
  ["김지원", "Jenny Kim"],
  ["길봉균", "Jayden Keel"],
  ["허재훈", "Joshua Hur"],
  ["장수재", "Daniel Jang"],
  ["이정권", "Jake Lee"],
  ["이병아", "Christine Lee"],
  ["김성혜", "Hailey Kim"],
  ["권정미", "Jamie Kwon"],
  ["백송이", "Lia Baek"],
  ["김주미", "Jenna Kim"],
  ["배수정", "Crystal Bae"],
  ["윤용식", "Steve Yoon"],
  ["최수경", "Sophia Choi"],
  ["이재윤", "Jay Lee"],
  ["김세민", "Selena Kim"],
  ["정성훈", "Ryan Jung"],
  ["신찬욱", "Anthony Shin"],
  ["이은경", "Emma Lee"]
];
